name: AutoTest

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: Ls files
        run: ls
      - name: Setup ENV
        run: . ./env_github/bin/activate
      - name: Setup ENV variables
        run: . .env.sh
