name: AutoTest

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup dependencies
        run: python install -r requirements.txt
      - name: Setup ENV variables
        run: sudo source env.sh
      - name: Run tests
        run: pytest -m tcid1
